server:
  port: 8762
spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ling07.top:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    password: lgr123456
    username: root
  redis:
    host: 115.28.138.45
    password: redispassword
    port: 6379
    #操作第几个库
    database: 0

    jedis:
      pool:
        #最大连接数
        max-active: 10
        #等待时间
        max-wait: 6000ms
        #最大空闲
        max-idle: 8
        #初始化最小
        min-idle: 5


#eureka:
#  client:
#    serviceUrl:
#      #defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://115.28.138.45:8761/eureka/
logging:
  level:
    root: info
    com.system.dao: debug
mybatis:
  mapper-locations: classpath:mybatis-mappers/*Dao.xml
  type-aliases-package: com.system.entity
