server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    #跳转链接
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html#/
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server